---

- name: Restart slapd
  service:
    name: slapd.service
    state: restarted
    daemon_reload: True
  become: True

- name: Restart saslauthd
  service: 
    name: saslauthd.service
    state: restarted
  become: True
